name: Deploy Node application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t fathismael93/sociopedia-server .
      - name: Publish Image to docker hub
        run: docker push fathismael93/sociopedia-server:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull fathismael93/sociopedia-server:latest
      - name: Delete old container
        run: docker rm -f sociopedia-server-container
      - name: Run Docker Container
        run: docker run -d -p 443:443 --name sociopedia-server-container -e MONGO_URL='${{ secrets.MONGO_URL }}' fathismael93/sociopedia-server
